Instrument DropwizardMetricsReporter
wavefrontHQ/wavefront-dropwizard-metrics-sdk-java pull request #31
Opened 2019-04-23 22:52 UTC by hanwavefront

2019-04-23 23:23 UTC, sushantdewan123 requested changes

2019-04-23 23:23 UTC, sushantdewan123 commented on src/main/java/com/wavefront/dropwizard/metrics/DropwizardMetricsReporter.java
> +        histogramsReported.inc();
ditto
break this into WavefrontHistogramReported and nonWavefrontHistogramReported

2019-04-23 23:39 UTC, vikramraman approved these changes

2019-04-24 00:28 UTC, sushantdewan123 requested changes
Use correct level 1 SDK.

2019-04-24 21:38 UTC, sushantdewan123 approved these changes

2019-04-24 21:38 UTC, merged